import Head from "next/head";
import Image from "next/image";
import { Inter } from "@next/font/google";
import styles from "@/styles/Home.module.css";
import profileFirst from "../assets/images/banner-01.jpg";
import profileSecord from "../assets/images/banner-02.jpg";
import profileThird from "../assets/images/banner-03.jpg";

const inter = Inter({ subsets: ["latin"] });

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className={styles.card_section}>
        <div className={styles.card}>
          <img src={profileFirst.src} alt="IMG-BANNER" />
          <div className={styles.card_body}>
            <h5>Women</h5>
            <p>Spring 2018</p>
            <a href="#">Shop Now</a>
          </div>
        </div>
        <div className={styles.card}>
          <img src={profileSecord.src} alt="IMG-BANNER" />
          <div className={styles.card_body}>
            <h5>Men</h5>
            <p>Spring 2018</p>
            <a href="#">Shop Now</a>
          </div>
        </div>
        <div className={styles.card}>
          <img src={profileThird.src} alt="IMG-BANNER" />
          <div className={styles.card_body}>
            <h5>Accessories</h5>
            <p>Spring 2018</p>
            <a href="#">Shop Now</a>
          </div>
        </div>
      </div>
      {/* end card section */}
      <div className="product-section">
        <div className="center_wr">
        <h2>Product Overview</h2>
        </div>
      </div>
    </>
  );
}
